// Fetch boards
export const BOARDS_FETCH_REQUEST = "BOARDS_FETCH_REQUEST";
export const BOARDS_FETCH_SUCCESS = "BOARDS_FETCH_SUCCESS";
export const BOARDS_FETCH_FAILURE = "BOARDS_FETCH_FAILURE";

// Create board
export const BOARDS_CREATE_REQUEST = "BOARDS_CREATE_REQUEST";
export const BOARDS_CREATE_SUCCESS = "BOARDS_CREATE_SUCCESS";
export const BOARDS_CREATE_FAILURE = "BOARDS_CREATE_FAILURE";
